when:
  - event: push
    branch:
      - main

steps:
  passed:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - echo "first step done"
  install:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - npm install
  test:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - ember test
