when:
  - event: push
    branch:
      - main

steps:
  build:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    on-error: ignore
    commands:
      - docker build
  test:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    on-error: ignore
    commands:
      - ember test
