when:
  - event: push
    branch:
      - main

steps:
  passed:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - echo "first step done"
  run:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - npm install
      - ember serve
  test:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - npm install
      - ember test
