when:
  - event: push
    branch:
      - main

steps:
  test:
    image: ${CI_DOCKER_BUILD_TAG}:1.0.0
    on-error: ignore
    commands:
      - npm install
      - ember test
  run:
    image: ${CI_DOCKER_BUILD_TAG}:1.0.0
    on-error: ignore
    commands:
      - npm install
      - ember serve
