steps:
  passed:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - echo "first step done"
      - echo ${CI_REPO}
  install:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - npm install
  build:
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: ${CI_REPO}
      tags: "latest"
    secrets: [docker_username, docker_password]

when:
  event: push
  branch:
    - master
