steps:
  passed:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - echo "first step done"
      - echo ${CI_REPO}
  build:
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: jonasvanhoof/portfolio-manager-frontend
      tags: "latest"
    secrets: [docker_username, docker_password]

when:
  event: tag
  tag: v*
  branch:
    - master
