steps:
  passed:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - echo "first step done"
      - echo ${CI_REPO}
      - echo ${CI_COMMIT_TAG##v}
  install:
    image: jonasvanhoof/portfolio-manager-frontend:1.0.0
    commands:
      - npm install
    when:
      event: push
      branch:
        - main
  # build:
  #   image: woodpeckerci/plugin-docker-buildx
  #   pull: true
  #   settings:
  #     repo: ${CI_REPO}
  #     tags: "${CI_COMMIT_TAG##v}"
  #   secrets: [docker_username, docker_password]
  #   when:
  #     event: tag
  #     tag: v*
  #     branch:
  #       - main
